homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 255
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  country: 'US'
  # Customization file
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url
  # Keymaster
  packages: !include_dir_named packages
system_health:
# Show links to resources in log and frontend
#introduction: 

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module   
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js
      type: module
    - url: /hacsfiles/numberbox-card/numberbox-card.js
      type: module                                
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module 

# If an item is excluded here, it will not show up on history or logbook pages
# history_graph won't work if the item is excluded here
recorder:
  db_url: !secret db_url
  purge_keep_days: 30
  exclude:
#    domains:
    entities:
      - sun.sun
      - sensor.date
      - sensor.date_time
      - sensor.internet_time
      - sensor.time_date
      - sensor.time_utc
      - sensor.time
      - sensor.uptime
history:
logbook:
# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
# Enables configuration UI
config:
# Enables sending Wake on Lan commands to other computers
wake_on_lan:
#
http:
  # ssl_certificate: /ssl/fullchain.pem  
  # ssl_key: /ssl/privkey.pem  
  # ssl_profile: intermediate
  cors_allowed_origins:  
   - https://google.com  
   - https://home-assistant.io  
  ip_ban_enabled: True  
  login_attempts_threshold: 5  
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.11.12.200


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:



# Track the sun
sun:

####################
##### Weather ######
####################

#switched to NWS
# weather:
  # - platform: darksky
    # api_key: !secret darksky_api
    # mode: daily

###############################
##### Push Notificatoins ######
###############################
notify:
  - platform: html5
    name: notify
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret email   
  - platform: group
    name: phones
    services:
      - service: mobile_app_trevor_s_s21_app
#      - service: mobile_app_emily

####################
##### Sensors ######
####################

binary_sensor:
  - platform: template
    sensors: 
      hallway_motion:
        friendly_name: "Hallway Motion"
        value_template: >-
          {%- if ((not is_state('sensor.hallway_motion_sensor_burglar', '0'))) -%}
            true
          {%- else -%}
            false
          {%- endif -%}
  # - platform: workday
    # country: US
sensor:
  # - platform: darksky
    # api_key: !secret darksky_api
    # monitored_conditions:
      # - temperature
    # scan_interval: '00:15:00'
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: template
    sensors:
      honeywell_temp:
        friendly_name: "Downstairs Temperature"
        unit_of_measurement: '°F'
        value_template: "{{ states.climate.thermostat.attributes.current_temperature }}"
      bathroom_humidity_diff:
        friendly_name: "Humidity difference between bathroom and house"
        unit_of_measurement: '%'
        value_template: "{{ states('sensor.bathroom_sensor_humidity')|float(0)|round(0) - states('sensor.home_humidity')|float(0)|round(0) }}"
      house_avg_temp:
        friendly_name: "Home Temperature"
        unit_of_measurement: '°F'
        value_template: >-
          {{ ((float(states.sensor.bedroom_temperature.state) + float(states.sensor.home_temperature.state) + float(states.sensor.living_room_temperature.state)) / 3) | round(2) }}
      temperature_0d:
        friendly_name: "Forecast - {{ as_timestamp(state_attr('weather.kbfi_daynight', 'forecast').0.datetime) | timestamp_custom('%a @ %H:%M') }}"
        unit_of_measurement: '°F'
        value_template: "{{ state_attr('weather.kbfi_daynight', 'forecast').0.temperature }}"
      temperature_1d:
        friendly_name: "Forecast - {{ as_timestamp(state_attr('weather.kbfi_daynight', 'forecast').1.datetime) | timestamp_custom('%a @ %H:%M') }}"
        unit_of_measurement: '°F'
        value_template: "{{ state_attr('weather.kbfi_daynight', 'forecast').1.temperature }}"
      temperature_2d:
        friendly_name: "Forecast - {{ as_timestamp(state_attr('weather.kbfi_daynight', 'forecast').2.datetime) | timestamp_custom('%a @ %H:%M') }}"
        unit_of_measurement: '°F'
        value_template: "{{ state_attr('weather.kbfi_daynight', 'forecast').2.temperature }}"
      temperature_3d:
        friendly_name: "Forecast - {{ as_timestamp(state_attr('weather.kbfi_daynight', 'forecast').3.datetime) | timestamp_custom('%a @ %H:%M') }}"
        unit_of_measurement: '°F'
        value_template: "{{ state_attr('weather.kbfi_daynight', 'forecast').3.temperature }}"
      temperature_4d:
        friendly_name: "Forecast - {{ as_timestamp(state_attr('weather.kbfi_daynight', 'forecast').4.datetime) | timestamp_custom('%a @ %H:%M') }}"
        unit_of_measurement: '°F'
        value_template: "{{ state_attr('weather.kbfi_daynight', 'forecast').4.temperature }}"
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

####################
##### Lights #######
####################

# this group is related to the "all lights" button in lovelace. Add a Light? Manually Update!  
light:
  - platform: group
    name: All Lights
    entities:
      - light.bathroom_light
      - light.bedroom_color_1
      - light.bedroom_color_2
      - light.bedroom_light
      - light.dining_lights
      - light.living_room
      - light.hallway_light
      - light.kitchen_light_1
      - light.kitchen_light_2
      - light.office_lights
      - light.office_lamp
      - light.spare_bedroom_lights
  - platform: group
    name: Dining Lights
    entities:
      - light.dining_room_1
      - light.dining_room_2
      - light.dining_room_3
      - light.dining_room_4
      - light.dining_room_5      

##########################
##### Input Boolean ######
##########################
input_boolean:
  coffee_set:
    name: Coffee pot is ready for brewing
    icon: mdi:coffee
  one_two_lamps:
    name: "Sunrise Alarm Lamp Number"
    icon: mdi:lamps
###########################
##### Device Tracker ######
###########################
device_tracker:
  - platform: unifi_direct
    host: 10.11.12.8
    username: !secret unifi_user
    password: !secret unifi_pw
    interval_seconds: 20
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
###### commented out until solution is found: https://github.com/home-assistant/core/issues/94189
  # - platform: bluetooth_tracker
    # interval_seconds: 6
    # consider_home: 120
    # new_device_defaults:
      # track_new_devices: false

###########################
#####  Thermostats   ######
###########################
ecobee:
  api_key: !secret ecobee_api_key
##################################
#####  Google Assistant     ######
################################## 
google_assistant: 
  project_id: !secret ga_project_id
  service_account: !include service_account.json
  report_state: true
  expose_by_default: false
  entity_config:
    light.bedroom_light:
      expose: true
      name: Bedroom Ceiling Light
    light.hallway_light:
      expose: true
      name: Hallway Light
    light.bathroom_light:
      expose: true
      name: Bathroom Lights
    light.kitchen_light_1:
      expose: true
      name: Kitchen Light 1
    light.kitchen_light_2:
      expose: true
      name: Kitchen Light 2
    switch.bathroom_fan:
      expose: true
      name: Bathroom Fan
    light.spare_bedroom_lights:
      expose: true
      name: Spare Bedroom Lights
    light.office_lights:
      expose: true
      name: Office Ceiling Light  
    switch.kitchen_plants:
      expose: true
      name: Kitchen Plants    
    switch.office_plants:
      expose: true
      name: Office Plants  
    switch.coffee:
      expose: true
      name: Coffee 
    switch.computer:
      expose: true
      name: Computer
###########################
#####     Switch     ######
###########################   
switch:
  - platform: wake_on_lan
    mac: !secret wol_mac
    host: !secret wol_host
    name: Computer

###########################
#####     Vacuum     ######
###########################   


###########################
###### Custom Panels ######
###########################


###########################
######  Mobile App   ######
###########################
mobile_app:

group: !include groups.yaml
automation: !include_dir_list automation

script: !include_dir_merge_named scripts

