homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 255
  # metric for Metric,  us_customary for USA
  unit_system:  us_customary
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  country: US
  currency: USD
  # Customization file
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url
  # Keymaster
  packages: !include_dir_named packages

group: !include groups.yaml
automation: !include automations.yaml
automation mine: !include_dir_list automation
script: !include_dir_merge_named scripts
template: !include template.yaml

system_health:
# Show links to resources in log and frontend
#introduction: 
my:
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module                                
    - url: /hacsfiles/scheduler-card/scheduler-card.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module 
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/numberbox-card/numberbox-card.js
      type: module
    - url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js
      type: module                                
# If an item is excluded here, it will not show up on history or logbook pages
# history_graph won't work if the item is excluded here
recorder:
  db_url: !secret db_url
  purge_keep_days: 30
  commit_interval: 30 # 30 seconds to reduce SD card wear
  exclude:
#    domains:
    entities:
      - sun.sun
      - sensor.date
      - sensor.date_time
      - sensor.internet_time
      - sensor.time_date
      - sensor.time_utc
      - sensor.time
      - sensor.uptime
      - sensor.next_hippo_departure_hrs
      - sensor.bermuda_global_total_device_count
      - sensor.bermuda_global_visible_device_count
    entity_globs:
      - sensor.*_distance_to_*    
      - binary_sensor.*_presence_*_target
history:

logbook:
  exclude:
    entity_globs:
    - sensor.*_last_seen
    - binary_sensor.*_presence_*_target
logger:
  default: warning
  logs:
    pychromecast.socket_client: fatal #socket connection error logs fill up logger otherwise, chromecast is just unstable
  filters:
    homeassistant.helpers.entity: # Honeywell servers are garbage
      - "Update of climate.thermostat is taking over 10 seconds"
# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
# Enables configuration UI
config:
# Enables sending Wake on Lan commands to other computers
wake_on_lan:
#
http:
  # ssl_certificate: /ssl/fullchain.pem  
  # ssl_key: /ssl/privkey.pem  
  # ssl_profile: intermediate
  cors_allowed_origins:  
   - https://google.com  
   - https://home-assistant.io  
  ip_ban_enabled: True  
  login_attempts_threshold: 5  
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.11.12.200


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# allows integrations to expose media for use
media_source:

# Track the sun
sun:

####################
##### Weather ######
####################
illuminance: #custom integration that roughly estimates LX based on current weather and sun elevation
  - unique_id: 1
    entity_id: weather.kbfi_daynight #service providing weather conditions
    fallback: 5 #1-10 scale of clear to cloudy if the above entity is unavailable
    mode: normal #'normal' is sun elevation, 'simple' uses time of day
    name: Weather-Based Sun Illuminance 
    scan_interval:
      minutes: 10 


###########################################
##### Push Notifications and Alerts  ######
###########################################
notify: 
  - platform: group
    name: 'all_devices'
    services:
      - service: mobile_app_s24u_trevor
      - service: mobile_app_s24u_emily
      - service: mobile_app_emily_s_tablet
  - platform: group
    name: 'phones'
    services:
      - service: mobile_app_s24u_trevor
      - service: mobile_app_s24u_emily
  - platform: tts
    name: tts_google_translate
    entity_id: tts.google_translate_en_com
    media_player: media_player.home_group
alert:
  leak_detection_dishwasher:
    name: 'Leak Detected'
    message: 'The dishwasher might be leaking'
    done_message: 'Water no longer detected'
    entity_id: binary_sensor.dishwasher_water_leak_sensor_water_leak_detected
    state: "on"
    repeat: 3
    can_acknowledge: true
    skip_first: false
    notifiers:
      - all_devices
      - tts_google_translate
  leak_detection_hot_water_heater:
    name: 'Leak Detected'
    message: 'The hot water tank might be leaking'
    done_message: 'Water no longer detected'
    entity_id: binary_sensor.hot_water_heater_water_leak_sensor_water_leak_detected
    state: "on"
    repeat: 3
    can_acknowledge: true
    skip_first: false
    notifiers:
      - all_devices
      - tts_google_translate      
  leak_detection_washer:
    name: 'Leak Detected'
    message: 'The laundry washer might be leaking'
    done_message: 'Water no longer detected'
    entity_id: binary_sensor.washer_water_leak_sensor_water_leak_detected
    state: "on"
    repeat: 3
    can_acknowledge: true
    skip_first: false
    notifiers:
      - all_devices
      - tts_google_translate
  garage_circuit:
    name: 'Possible Power Loss'
    message: 'Garage Freezer is no longer drawing power'
    done_message: 'Power has been restored'
    entity_id: device_tracker.uap_ac_lite #device is on the same circuit as the garage freezer
    state: "not_home"
    repeat: 
      - 20
      - 10
      - 30
    can_acknowledge: true
    skip_first: true #prevents alerting if it blinks off, but will alert during extended power loss situations
    notifiers:
      - all_devices

####################
##### Sensors ######
####################

binary_sensor:
  - platform: template
    sensors: 
      hallway_motion:
        friendly_name: "Hallway Motion"
        value_template: >-
          {%- if ((not is_state('sensor.hallway_motion_sensor_burglar', '0'))) -%}
            true
          {%- else -%}
            false
          {%- endif -%}
  # wrapping my head around bayesian sensors. Think of it as "Assume X is true (the event of the sensor), what observations are also likely to be true? 
  - platform: bayesian
    name: "In bed but might be awake"
    unique_id: bed_presence
    prior: 0.5 # roughly 12 hours a day in the bedroom (awake or asleep)
    probability_threshold: 0.7 # I'd rather be conservative than turn lights on accidentally
    observations:
      - platform: state
        entity_id: sensor.trevor_ble_area
        prob_given_true: 0.63 # phone bounces between the office and bedroom BLE sensors often (false negative)
        prob_given_false: 0.166 # Bedroom BLE sensor rarely gives false positives
        to_state: 'Bedroom' #case sensitive
      - platform: state
        entity_id: sensor.emily_ble_area
        prob_given_true: 0.71 # phone bounces between the office and bedroom BLE sensors often (false negative)
        prob_given_false: 0.04166 # Bedroom BLE sensor rarely gives false positives
        to_state: 'Bedroom' #case sensitive
      - platform: state
        entity_id: sensor.trevor_phone_charger_type
        prob_given_true: 0.58 # I'm most likely charging the phone if I'm in bed
        prob_given_false: 0.083 # When I am awake, I occasionally wirelessly charge my phone
        to_state: 'wireless'
      - platform: state
        entity_id: sensor.emily_phone_charger_type
        prob_given_true: 0.67 # She's most likely charging the phone if she i in bed
        prob_given_false: 0.083 # When she is awake, she occasionally wirelessly charges her phone
        to_state: 'wireless'
      - platform: state
        entity_id: binary_sensor.bedroom_presence_presence
        prob_given_true: 0.71 # pretty accurate that either me or my partner is in the room
        prob_given_false: 0.25 # sometimes we go into the bedroom during the day
        to_state: 'on'
      - platform: state
        entity_id: binary_sensor.all_but_bedroom_presence
        prob_given_true: 0.04 # sometimes a cat triggers it at night
        prob_given_false: 0.916 # normal hours
        to_state: 'on'

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'


####################
##### Lights #######
####################

# this group is related to the "all lights" button in lovelace. Add a Light? Manually Update!  
light:
  - platform: group
    name: All Lights
    entities:
      - light.bathroom_light
      - light.bedroom_color_1
      - light.bedroom_color_2
      - light.bedroom_light
      - light.dining_lights
      - light.living_room
      - light.hallway_light
      - light.kitchen_light_1
      - light.kitchen_light_2
      - light.office_light
      - light.office_lamp
      - light.spare_bedroom_light
      - light.kitchen_sink
  - platform: group
    name: Dining Lights
    entities:
      - light.dining_room_1
      - light.dining_room_2
      - light.dining_room_3
      - light.dining_room_4
      - light.dining_room_5      
  - platform: group
    name: All Kitchen Lights
    entities:
      - light.kitchen_light_1
      - light.kitchen_light_2
      - light.kitchen_sink
  - platform: group
    name: Ceiling Kitchen Lights
    entities:
      - light.kitchen_light_1
      - light.kitchen_light_2
  - platform: group
    name: All Bedroom Lights
    entities:
      - light.bedroom_color_1
      - light.bedroom_color_2
      - light.bedroom_light    
##########################
##### Input Boolean ######
##########################
input_boolean:
  coffee_set:
    name: Coffee pot is ready for brewing
    icon: mdi:coffee
  one_two_lamps:
    name: "Sunrise Alarm Lamp Number"
    icon: mdi:lamps
  ac_or_furnace:
    name: "AC or Furnace operational"
    icon: mdi:sun-snowflake-variant
## Used as a condition to let presence automations fire or not
  bathroom_light_auto_on:
    name: "Automations can turn on the bathroom light"
    initial: on
  bedroom_color_1_auto_on:
    name: "Automatically turned on Trevor's lamp"
    initial: on
  bedroom_color_2_auto_on:
    name: "Automatically turned on Emily's lamp"
    initial: on
  bedroom_light_auto_on:
    name: "Automations can turn on the bedroom ceiling light"
    initial: on
  christmas_tree_auto_on:
    name: "Automations can turn on the Christmas Tree"
    initial: on
  dining_lights_auto_on:
    name: "Automations can turn on the dining lights"
    initial: on
  hallway_light_auto_on:
    name: "Automations can turn on the hallway light"
    initial: on
  kitchen_light_1_auto_on:
    name: "Automations can turn on the kitchen 1 light"
    initial: on
  kitchen_light_2_auto_on:
    name: "Automations can turn on the kitchen 2 light"
    initial: on
  living_room_light_auto_on:
    name: "Automations can turn on the living room light"
    initial: on
  office_lamp_auto_on:
    name: "Automations can turn on the office lamp"
    initial: on
  office_light_auto_on:
    name: "Automations can turn on the office light"
    initial: on
  spare_bedroom_light_auto_on:
    name: "Automations can turn on the spare bedroom light"
    initial: on
###########################
##### Device Tracker ######
###########################
device_tracker:
  - platform: unifi_direct
    host: 10.11.12.3
    username: !secret unifi_user
    password: !secret unifi_pw
    interval_seconds: 20
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
  # - platform: unifi_direct
    # host: 10.11.12.4
    # username: !secret unifi_user
    # password: !secret unifi_pw
    # interval_seconds: 20
    # consider_home: 180
    # new_device_defaults:
      # track_new_devices: false



##################################
#####  Google Assistant     ######
################################## 
google_assistant: 
  project_id: !secret ga_project_id
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  expose_by_default: false
  entity_config:
    light.bedroom_light:
      expose: true
      name: Bedroom Ceiling Light
    light.hallway_light:
      expose: true
      name: Hallway Light
    light.bathroom_light:
      expose: true
      name: Bathroom Lights
    light.kitchen_light_1:
      expose: true
      name: Kitchen Light 1
    light.kitchen_light_2:
      expose: true
      name: Kitchen Light 2
    switch.bathroom_fan:
      expose: true
      name: Bathroom Fan
    light.spare_bedroom_light:
      expose: true
      name: Spare Bedroom Lights
    light.office_light:
      expose: true
      name: Office Ceiling Light  
    switch.kitchen_plants:
      expose: true
      name: Kitchen Plants    
    switch.office_plants:
      expose: true
      name: Office Plants  
    switch.coffee:
      expose: true
      name: Coffee 
    switch.computer:
      expose: true
      name: Computer
    climate.the_hippo_hvac_climate_system:
      expose: True
      name: The Hippo
        
###########################
#####     Switch     ######
###########################   
switch:
  - platform: wake_on_lan
    mac: !secret wol_mac
    host: !secret wol_host
    name: Computer
  - platform: template
    switches:
      ac_or_furnace:
        friendly_name: "{{ 'Furnace' if is_state('input_boolean.ac_or_furnace', 'on') else 'A/C' }}"
        value_template: "{{ is_state('input_boolean.ac_or_furnace','on') }}"
        turn_on:
          action: input_boolean.turn_on
          target:
            entity_id: input_boolean.ac_or_furnace
        turn_off:
          action: input_boolean.turn_off
          target:
            entity_id: input_boolean.ac_or_furnace
        icon_template: >-
          {% if is_state('input_boolean.ac_or_furnace', 'on') %}
            mdi:hvac
          {% else %}
            mdi:air-conditioner
          {% endif %}
      coffee_set:
        friendly_name: "{{ 'Ready to Brew' if is_state('input_boolean.coffee_set', 'on') else 'Not Ready' }}"
        value_template: "{{ is_state('input_boolean.coffee_set','on') }}"
        turn_on:
          action: input_boolean.turn_on
          target:
            entity_id: input_boolean.coffee_set
        turn_off:
          action: input_boolean.turn_off
          target:
            entity_id: input_boolean.coffee_set
        icon_template: >-
          {% if is_state('input_boolean.coffee_set', 'on') %}
            mdi:coffee
          {% else %}
            mdi:coffee-off
          {% endif %}
      one_two_lamps:
        friendly_name: "{{ 'Both Lamps' if is_state('input_boolean.one_two_lamps', 'on') else 'One Lamp' }}"
        value_template: "{{ is_state('input_boolean.one_two_lamps','on') }}"
        turn_on:
          action: input_boolean.turn_on
          target:
            entity_id: input_boolean.one_two_lamps
        turn_off:
          action: input_boolean.turn_off
          target:
            entity_id: input_boolean.one_two_lamps
        icon_template: >-
          {% if is_state('input_boolean.one_two_lamps', 'on') %}
            mdi:lamps
          {% else %}
            mdi:lamp
          {% endif %}
##################################
##### Unversal Media Player ######
################################## 
  
media_player:
  - platform: universal
    name: living_room_tv
    unique_id: living_room_tv
    device_class: tv
    attributes:
      state: media_player.smart_tv_pro_2
    children:
      - media_player.smart_tv_pro_2
      - media_player.smart_tv_pro
 #     - remote.harmony_hub
    browse_media_entity: media_player.smart_tv_pro
    commands:
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.smart_tv_pro_2
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.smart_tv_pro_2
      volume_up:
        service: remote.send_command
        target:
          entity_id: remote.harmony_hub
        data:
          device: 40193695
          command: VolumeUp
      volume_down:
        service: remote.send_command
        target:
          entity_id: remote.harmony_hub
        data:
          device: 40193695
          command: VolumeDown
      volume_mute:
        service: remote.send_command
        target:
          entity_id: remote.harmony_hub
        data:
          device: 40193695
          command: Mute

###########################
###### Custom Panels ######
###########################


###########################
######  Mobile App   ######
###########################
mobile_app:

