title: Home

preload:
  - entity-filter
views:
  - title: Status
    icon: mdi:home
    cards:      
      - type: vertical-stack
        cards:
        - type: entity-filter
          entities: !include devices.yaml
          state_filter:
            - home        
          card:
            type: glance
            title: Location        
        - type: horizontal-stack
          cards:
          - type: button
            entity: lock.lock_front_door_lock
            tap_action: 
              action: toggle
          - type: conditional
            conditions:
              - entity: sensor.front_door_lock_battery_level 
                state_not: "unknown"
            card:
              type: gauge
              entity: sensor.front_door_lock_battery_level 
              name: Door Battery
              severity:
                green: 85
                yellow: 45
                red: 0          
      - type: weather-forecast
        entity: weather.kbfi_hourly
      - type: vertical-stack
        cards:
        - type: light
          entity: light.all_lights
        - type: horizontal-stack
          cards:
            - type: button
              entity: switch.kitchen_plants
              icon: mdi:cactus
              icon_height: 100px
            - type: button
              entity: switch.office_plants
              icon: mdi:sprout
              icon_height: 100px            
      - type: 'custom:paper-buttons-row'
        buttons:
          - entity: switch.coffee
            icon: mdi:coffee-maker
            align_icon: top
            style:
              icon:
                --mdc-icon-size: 100px      
              # button:
                # background-color: var(--table-row-alternative-background-color)
            tap_action:
              action: call-service 
              service: homeassistant.turn_on
              service_data:
                entity_id: script.coffee_start

          - entity: input_boolean.coffee_set
            align_icon: top
            name: false
            layout: icon_state
            state_icons:
              "off": "mdi:coffee-off"
              "on": "mdi:coffee"
            state_text:
              "off": "not ready to brew"
              "on": "coffee is set"
            style:
              icon:
                --mdc-icon-size: 100px 
          - entity: input_boolean.one_two_lamps
            align_icon: top
            name: false
            layout: icon_state
            state_icons:
              "off": "mdi:lamp"
              "on": "mdi:lamps"
            state_text:
              "off": "Just One Lamp"
              "on": "Both Lamps"
            style:
              icon:
                --mdc-icon-size: 100px                 
      - type: 'custom:vertical-stack-in-card'
        cards:
          - type: 'custom:mini-graph-card'
            title: Temperatures
            hours_to_show: 12
            points_per_hour: 1
            hour24: true
            decimals: 0
            entities:
              - sensor.house_avg_temp
              - sensor.honeywell_temp

          - type: horizontal-stack
            cards:
              - type: 'custom:simple-thermostat'
                entity: climate.home
                name: Upstairs
                decimals: 0
                step_size: 1
                fallback: '00'
                label:
                  temperature: Temp
                control:
                  hvac:
                    cool:
                      include: false
                    heat:
                      include: false
                    'off':
                      include: false                
              - type: 'custom:simple-thermostat'
                entity: climate.thermostat
                name: Basement
                decimals: 0
                step_size: 1
                fallback: '00'
                label: 
                  temperature: Temp
                control:
                  hvac:
                    cool:
                      include: false
                    heat:
                      include: false
                    'off':
                      include: false

          - type: horizontal-stack
            cards:
            - type: thermostat
              entity: climate.window_a_c
              name: Air Conditioner
              decimals: 0
              step_size: 1
              # control:
                # hvac:
                  # cool:
                    # include: false
                  # heat:
                    # include: false
                  # 'off':
                    # include: false
            # - type: 'custom:mini-graph-card'
              # title: A/C Power
              # entities: 
                # - sensor.window_a_c_energy_current
      - type: 'custom:vertical-stack-in-card'
        cards:
          - type: 'custom:mini-graph-card'
            title: Humidity
            hours_to_show: 12
            points_per_hour: 1
            hour24: true
            decimals: 0
            entities:
              - sensor.bathroom_sensor_humidity
              - sensor.home_humidity
          - type: horizontal-stack
            cards:
            - type: button
              entity: switch.bathroom_fan
              tap_action:  
                action: toggle  
            - type: gauge
              entity: sensor.bathroom_humidity_diff
              name: Humidity Diff.             
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: glance
            title: Hass.io
            entities:
              - entity: sensor.cert_expiry_timestamp_home_trevortaylor_net
                name: SSL Cert Expiry
              - entity: sensor.uptime
                name: Uptime
          - type: button
            entity: switch.computer
            name: Computer
            icon: mdi:desktop-tower-monitor
            icon_height: 100px           
        - type: glance
          title: AdGuard
          entities:
            - entity: sensor.adguard_dns_queries_blocked
              name: Total
            - entity: sensor.adguard_dns_queries_blocked_ratio
              name: Blocked
            - entity: switch.adguard_protection
              name: Active
              tap_action: 
                action: toggle
  - title: Lights
    icon: mdi:lightbulb
    cards:
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.hallway_light
        - type: light
          entity: light.bathroom_light
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.office_lamp
        - type: light
          entity: light.office_lights
          name: Office Ceiling Light

      - type: horizontal-stack
        cards:
        - type: light
          entity: light.spare_bedroom_lights
        - type: light
          entity: light.living_room
      - type: 'custom:vertical-stack-in-card'
        cards:
        - type: light
          entity: light.bedroom_light      
          name: Bedroom Ceiling Light
        - type: horizontal-stack
          cards:
          - type: light
            entity: light.bedroom_color_1
          - type: light
            entity: light.bedroom_color_2
            name: Emily's Lamp
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.kitchen_light_1
        - type: light
          entity: light.kitchen_light_2
      - type: 'custom:vertical-stack-in-card'
        cards:
          - type: light
            entity: light.dining_lights
          - type: glance
            show_name: false
            entities:
              - entity: light.dining_room_1
                tap_action:  
                  action: toggle
              - entity: light.dining_room_2
                tap_action:  
                  action: toggle
              - entity: light.dining_room_3
                tap_action:  
                  action: toggle
              - entity: light.dining_room_4
                tap_action:  
                  action: toggle
              - entity: light.dining_room_5
                tap_action:  
                  action: toggle
      - type: horizontal-stack
        cards:
          - type: button
            entity: switch.kitchen_plants
            icon: mdi:cactus
            icon_height: 100px
          - type: button
            entity: switch.office_plants
            icon: mdi:sprout
            icon_height: 100px  
  - title: Media Players
    icon: mdi:television
    cards:
      - type: 'custom:vertical-stack-in-card'
        cards:
        - type: conditional
          conditions:
            - entity: media_player.chromecast
              state: "playing"
          card:
            type: custom:mini-media-player
            entity: media_player.chromecast
            artwork: full-cover
            name: Plex
            icon: mdi:plex
            hide: 
              volume: true
              power: true  
              controls: true
              name: true
        - type: conditional
          conditions:
            - entity: media_player.chromecast
              state: "paused"
          card:
            type: custom:mini-media-player
            entity: media_player.chromecast
            artwork: full-cover
            name: Plex
            icon: mdi:plex
            hide: 
              volume: true
              power: true  
              controls: true
              name: true
        - type: custom:mini-media-player
          entity: media_player.chromecast
          artwork: full-cover
          name: Plex
          icon: mdi:plex
          hide: 
            volume: true
            power: true 
            progress: true
        - type: horizontal-stack
          cards:
          - type: 'custom:vertical-stack-in-card'
            cards:
            - type: button
              name: System Power
              icon: mdi:power
              entity: remote.harmony_hub
              tap_action:  
                action: toggle
            - type: button
              name: "Mute / Unmute"
              icon: mdi:volume-off
              entity: remote.harmony_hub
              tap_action:  
                action: call-service
                service: remote.send_command
                service_data:
                  entity_id: remote.harmony_hub
                  device: 40193695
                  command: Mute
          - type: 'custom:vertical-stack-in-card'
            cards:
            - type: button
              name: Volume Up
              icon: mdi:volume-high
              entity: remote.harmony_hub
              tap_action:  
                action: call-service
                service: remote.send_command
                service_data:
                  entity_id: remote.harmony_hub
                  device: 40193695
                  command: VolumeUp
            - type: button
              name: Volume Down
              icon: mdi:volume-low
              entity: remote.harmony_hub
              tap_action:  
                action: call-service
                service: remote.send_command
                service_data:
                  entity_id: remote.harmony_hub
                  device: 40193695
                  command: VolumeDown
        - type: sensor
          name: Current Plex Streams
          entity: sensor.plex_huginn

      - type: horizontal-stack
        cards:
        - type: custom:mini-media-player
          artwork: cover
          entity: media_player.home_group
          hide:
            power: true
        - type: custom:mini-media-player
          artwork: cover
          entity: media_player.tv_and_speakers
          hide:
            power: true
      - type: vertical-stack
        cards:      
        - type: custom:mini-media-player
          entity: media_player.bedroom_speaker
          artwork: cover
          hide:
            power: true
        - type: custom:mini-media-player
          entity: media_player.kitchen_speaker
          artwork: cover
          hide:
            power: true
        - type: custom:mini-media-player
          entity: media_player.bathroom_speaker
          artwork: cover
          hide:
            power: true