title: Home

preload:
  - entity-filter
views:
  - title: Status
    icon: mdi:home
    cards:      
      - type: 'custom:vertical-stack-in-card'
        cards:
        - type: entity-filter
          entities: !include devices.yaml
          state_filter:
            - home        
          card:
            type: glance
            title: Location        
        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: lock.lock_front_door_lock
            tap_action: 
              action: toggle
          - type: conditional
            conditions:
              - entity: sensor.schlage_lock_battery_level 
                state_not: "unknown"
            card:
              type: gauge
              entity: sensor.schlage_lock_battery_level 
              name: Door Battery
              severity:
                green: 85
                yellow: 45
                red: 0          

      - type: 'custom:vertical-stack-in-card'
        cards:
        # - type: 'custom:mini-graph-card'
          # title: Temperatures
          # hours_to_show: 24
          # points_per_hour: 1
          # hour24: true
          # decimals: 0
          # action: none
          # show:
            # name: false
            # icon: false
            # points: false
            # extrema: true
            # state: false            
          # entities:
            # - sensor.dark_sky_temperature
        - type: weather-forecast
          entity: weather.kbfi_hourly
      - type: light
        entity: light.all_lights
      - type: horizontal-stack
        cards:
          - type: button
            entity: switch.kitchen_plants
            icon: mdi:cactus
            icon_height: 100px
          - type: button
            entity: switch.office_plants
            icon: mdi:sprout
            icon_height: 100px            
      - type: 'custom:vertical-stack-in-card'
        cards:
          - type: 'custom:mini-graph-card'
            title: Temperatures
            hours_to_show: 12
            points_per_hour: 1
            hour24: true
            decimals: 0
            entities:
              - sensor.house_avg_temp
              - sensor.honeywell_temp

          - type: horizontal-stack
            cards:
              - type: 'custom:simple-thermostat'
                entity: climate.home
                name: Upstairs
                decimals: 0
                step-size: 1
                fallback: '00'
                label:
                  temperature: Temp
                control:
                  hvac:
                    cool:
                      include: false
                    heat:
                      include: false
                    'off':
                      include: false                
              - type: 'custom:simple-thermostat'
                entity: climate.thermostat
                name: Basement
                decimals: 0
                step-size: 1
                fallback: '00'
                label: 
                  temperature: Temp
                control:
                  hvac:
                    cool:
                      include: false
                    heat:
                      include: false
                    'off':
                      include: false

      - type: 'custom:vertical-stack-in-card'
        cards:
          - type: 'custom:mini-graph-card'
            title: Humidity
            hours_to_show: 12
            points_per_hour: 1
            hour24: true
            decimals: 0
            entities:
              - sensor.bathroom_sensor_relative_humidity
              - sensor.home_humidity
          - type: horizontal-stack
            cards:
            - type: entity-button
              entity: switch.bathroom_fan_switch
              tap_action:  
                action: toggle  
            - type: gauge
              entity: sensor.bathroom_humidity_diff
              name: Humidity Diff.             
      - type: horizontal-stack
        cards:
        - type: glance
          title: Hass.io
          entities:
            - entity: sensor.ssl_certificate_expiry
              name: SSL Cert Expiry
            - entity: sensor.uptime
              name: Uptime
        - type: glance
          title: AdGuard
          entities:
            - entity: sensor.adguard_dns_queries_blocked
              name: Total
            - entity: sensor.adguard_dns_queries_blocked_ratio
              name: Blocked
            - entity: switch.adguard_protection
              name: Active
              tap_action: 
                action: toggle

  - title: Lights
    icon: mdi:lightbulb
    cards:
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.hallway_lightswitch_level
        - type: light
          entity: light.bathroom_lightswitch_level
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.office_lamp
        - type: light
          entity: light.office_lightswitch_level
          name: Office Ceiling Light

      - type: horizontal-stack
        cards:
        - type: light
          entity: light.spare_bedroom_lightswitch_level
        - type: light
          entity: light.living_room
      - type: 'custom:vertical-stack-in-card'
        cards:
        - type: light
          entity: light.bedroom_lightswitch_level      
          name: Bedroom Ceiling Light
        - type: horizontal-stack
          cards:
          - type: light
            entity: light.bedroom_color_1
          - type: light
            entity: light.bedroom_color_2
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.kitchen_lightswitch_1_level
        - type: light
          entity: light.kitchen_lightswitch_2_level
      - type: 'custom:vertical-stack-in-card'
        cards:
          - type: light
            entity: light.dining
          - type: glance
            show_name: false
            entities:
              - entity: light.dining_room_1
                tap_action:  
                  action: toggle
              - entity: light.dining_room_2
                tap_action:  
                  action: toggle
              - entity: light.dining_room_3
                tap_action:  
                  action: toggle
              - entity: light.dining_room_4
                tap_action:  
                  action: toggle
              - entity: light.dining_room_5
                tap_action:  
                  action: toggle
      - type: horizontal-stack
        cards:
          - type: button
            entity: switch.kitchen_plants
            icon: mdi:cactus
            icon_height: 100px
          - type: button
            entity: switch.office_plants
            icon: mdi:sprout
            icon_height: 100px  
  - title: Media Players
    icon: mdi:television
    cards:
      - type: vertical-stack
        cards:
        - type: entity-button
          name: Chromecast
          icon: mdi:television
          entity: remote.harmony_hub
          tap_action:  
            action: toggle
        - type: media-control
          entity: media_player.chromecast
      - type: vertical-stack
        cards:
        - type: media-control
          entity: media_player.home_group
        - type: media-control
          entity: media_player.tv_and_speakers
        - type: media-control
          entity: media_player.living_room_speaker        
      - type: vertical-stack
        cards:      
        - type: media-control
          entity: media_player.bedroom_speaker
        - type: media-control
          entity: media_player.kitchen_speaker
        - type: media-control
          entity: media_player.bathroom_speaker