title: Home
views:
  - title: Status
    icon: mdi:home
    cards:
      - type: conditional
        conditions:
          - entity: group.all_automations
            state: "off"
        card:
          type: entities
          entities:
            - group.all_automations          
      - type: weather-forecast
        entity: weather.dark_sky
      - type: light
        entity: light.all_lights
      - type: entity-filter
        entities: !include devices.yaml
        state_filter:
          - home
        card:
          type: glance
          title: Location
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: thermostat
                entity: climate.home
              - type: thermostat
                entity: climate.thermostat
          - type: history-graph
            title: Temperatures
            hours_to_show: 24
            refresh_interval: 1800
            entities:
              - sensor.house_avg_temp
              - sensor.dark_sky_temperature
              - sensor.honeywell_temp
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
            - type: entity-button
              entity: switch.bathroom_fan_switch
              tap_action:  
                action: toggle  
            - type: gauge
              entity: sensor.bathroom_humidity_diff
              title: Humidity Diff.

          - type: history-graph
            title: Humidity
            hours_to_show: 24
            refresh_interval: 600
            entities:
              - sensor.bathroom_sensor_relative_humidity
              - sensor.home_humidity            
      - type: horizontal-stack
        cards:
        - type: glance
          title: Hass.io
          entities:
            - entity: sensor.ssl_certificate_expiry
              name: SSL Cert Expiry
            - entity: sensor.uptime
              name: Uptime
        - type: glance
          title: Pi-Hole
          entities:
            - entity: sensor.pi_hole_ads_blocked_today
              name: Total
            - entity: sensor.pi_hole_ads_percentage_blocked_today
              name: Blocked
      - type: horizontal-stack
        cards:
        - type: entity-button
          entity: lock.lock_front_door_lock
          tap_action: 
            action: toggle
        - type: conditional
          conditions:
            - entity: sensor.frontdoorbattery
              state_not: "unknown"
          card:
            type: gauge
            entity: sensor.frontdoorbattery
            title: Door Battery
  - title: Lights
    icon: mdi:lightbulb
    cards:
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.hallway_lightswitch_level
        - type: light
          entity: light.bathroom_lightswitch_level
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.spare_bedroom_lightswitch_level
        - type: light
          entity: light.office_lightswitch_level
      - type: light
        entity: light.living_room
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.bedroom_color_2
        - type: light
          entity: light.bedroom_lightswitch_level
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.kitchen_lightswitch_1_level
        - type: light
          entity: light.kitchen_lightswitch_2_level
      - type: vertical-stack
        cards:
          - type: light
            entity: light.dining
          - type: glance
            show_name: false
            entities:
              - entity: light.dining_room_1
                tap_action:  
                  action: toggle
              - entity: light.dining_room_2
                tap_action:  
                  action: toggle
              - entity: light.dining_room_3
                tap_action:  
                  action: toggle
              - entity: light.dining_room_4
                tap_action:  
                  action: toggle
              - entity: light.dining_room_5
                tap_action:  
                  action: toggle
  - title: Media Players
    icon: mdi:television
    cards:
      - type: vertical-stack
        cards:
        - type: entity-button
          name: Chromecast
          icon: mdi:television
          entity: remote.harmony_hub
          tap_action:  
            action: toggle
        - type: media-control
          entity: media_player.chromecast
      - type: vertical-stack
        cards:
        - type: media-control
          entity: media_player.home_group
        - type: media-control
          entity: media_player.tv_and_speakers
        - type: media-control
          entity: media_player.living_room_speaker        
      - type: vertical-stack
        cards:      
        - type: media-control
          entity: media_player.bedroom_speaker
        - type: media-control
          entity: media_player.kitchen_speaker
        - type: media-control
          entity: media_player.bathroom_speaker
  - title: Door Lock Entry Codes
    icon: mdi:dialpad
    cards:
      - type: entities
        title: Entry Code 1
        show_header_toggle: false
        entities:
          - input_text.door_keypad_1_name
          - input_text.door_keypad_1_code
          - input_select.door_keypad_1_access_schedule
          - input_datetime.door_keypad_1_date_start
          - input_datetime.door_keypad_1_date_end
          - input_boolean.door_keypad_1_front_switch
          - script.door_keypad_1_delete
      - type: entities
        title: Entry Code 2
        show_header_toggle: false
        entities:
          - input_text.door_keypad_2_name
          - input_text.door_keypad_2_code
          - input_select.door_keypad_2_access_schedule
          - input_datetime.door_keypad_2_date_start
          - input_datetime.door_keypad_2_date_end
          - input_boolean.door_keypad_2_front_switch
          - script.door_keypad_2_delete
      - type: entities
        title: Entry Code 3
        show_header_toggle: false
        entities:
          - input_text.door_keypad_3_name
          - input_text.door_keypad_3_code
          - input_select.door_keypad_3_access_schedule
          - input_datetime.door_keypad_3_date_start
          - input_datetime.door_keypad_3_date_end
          - input_boolean.door_keypad_3_front_switch
          - script.door_keypad_3_delete
      - type: entities
        title: Entry Code 4
        show_header_toggle: false
        entities:
          - input_text.door_keypad_4_name
          - input_text.door_keypad_4_code
          - input_select.door_keypad_4_access_schedule
          - input_datetime.door_keypad_4_date_start
          - input_datetime.door_keypad_4_date_end
          - input_boolean.door_keypad_4_front_switch
          - script.door_keypad_4_delete
      - type: entities
        title: Entry Code 5
        show_header_toggle: false
        entities:
          - input_text.door_keypad_5_name
          - input_text.door_keypad_5_code
          - input_select.door_keypad_5_access_schedule
          - input_datetime.door_keypad_5_date_start
          - input_datetime.door_keypad_5_date_end
          - input_boolean.door_keypad_5_front_switch
          - script.door_keypad_5_delete
      - type: entities
        title: Entry Code 6
        show_header_toggle: false
        entities:
          - input_text.door_keypad_6_name
          - input_text.door_keypad_6_code
          - input_select.door_keypad_6_access_schedule
          - input_datetime.door_keypad_6_date_start
          - input_datetime.door_keypad_6_date_end
          - input_boolean.door_keypad_6_front_switch
          - script.door_keypad_6_delete
      - type: entities
        title: Entry Code 7
        show_header_toggle: false
        entities:
          - input_text.door_keypad_7_name
          - input_text.door_keypad_7_code
          - input_select.door_keypad_7_access_schedule
          - input_datetime.door_keypad_7_date_start
          - input_datetime.door_keypad_7_date_end
          - input_boolean.door_keypad_7_front_switch
          - script.door_keypad_7_delete
      - type: entities
        title: Entry Code 8
        show_header_toggle: false
        entities:
          - input_text.door_keypad_8_name
          - input_text.door_keypad_8_code
          - input_select.door_keypad_8_access_schedule
          - input_datetime.door_keypad_8_date_start
          - input_datetime.door_keypad_8_date_end
          - input_boolean.door_keypad_8_front_switch
          - script.door_keypad_8_delete
      - type: entities
        title: Entry Code 9
        show_header_toggle: false
        entities:
          - input_text.door_keypad_9_name
          - input_text.door_keypad_9_code
          - input_select.door_keypad_9_access_schedule
          - input_datetime.door_keypad_9_date_start
          - input_datetime.door_keypad_9_date_end
          - input_boolean.door_keypad_9_front_switch
          - script.door_keypad_9_delete
      - type: entities
        title: Entry Code 10
        show_header_toggle: false
        entities:
          - input_text.door_keypad_10_name
          - input_text.door_keypad_10_code
          - input_select.door_keypad_10_access_schedule
          - input_datetime.door_keypad_10_date_start
          - input_datetime.door_keypad_10_date_end
          - input_boolean.door_keypad_10_front_switch
          - script.door_keypad_10_delete
  - title: One Time Use Entry Codes
    icon: mdi:bomb
    cards:
      - type: entities
        title: One Time Use Code 1
        show_header_toggle: false
        entities:
          - input_select.door_keypad_16_access_schedule
          - input_text.door_keypad_16_name
          - input_text.door_keypad_16_code
          - input_boolean.door_keypad_16_front_switch
          - script.door_keypad_16_delete
      - type: entities
        title: One Time Use Code 2
        show_header_toggle: false
        entities:
          - input_select.door_keypad_17_access_schedule
          - input_text.door_keypad_17_name
          - input_text.door_keypad_17_code
          - input_boolean.door_keypad_17_front_switch
          - script.door_keypad_17_delete
      - type: entities
        title: One Time Use Code 3
        show_header_toggle: false
        entities:
          - input_select.door_keypad_18_access_schedule
          - input_text.door_keypad_18_name
          - input_text.door_keypad_18_code
          - input_boolean.door_keypad_18_front_switch
          - script.door_keypad_18_delete