light.hallway_light:
  ignored: false
  refresh_value: true
  polling_intensity: 1
  delay: 3
light.bedroom_light:
  ignored: false
  refresh_value: true
  polling_intensity: 1
  delay: 3
light.bathroom_light:
  ignored: false
  refresh_value: true
  polling_intensity: 1
  delay: 3
light.kitchen_light_1:
  ignored: false
  refresh_value: true
  polling_intensity: 1
  delay: 3
light.kitchen_light_2:
  ignored: false
  refresh_value: true
  polling_intensity: 1
  delay: 3
light.office_lightswitch_level:
  ignored: false
  refresh_value: true
  polling_intensity: 1
  delay: 3
light.spare_bedroom_lights:
  ignored: false
  refresh_value: true
  polling_intensity: 1
  delay: 3  