alias: 'Bathroom Humidity Difference'
id: bathroom_humidity_difference
# if the bathroom humidity is above house's by 10% and over 70%, start bathroom fan until it is under 60% humidity
trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_sensor_humidity
    above: '70'
condition:
  condition: numeric_state
  entity_id: sensor.bathroom_humidity_diff
  above: '10'
action:
# waits 5 min before starting the fan
  - delay: 00:05:00
  - service: homeassistant.turn_on
    entity_id: script.bathroom_humidity