alias: 'Bathroom Humidity Difference'
# if the bathroom humidity is above house's by 10% and over 60%, start bathroom fan for 10 min or until it is within 10% of house humidity
trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_sensor_relative_humidity
    above: '60'
condition:
  condition: numeric_state
  entity_id: sensor.bathroom_humidity_diff
  above: '10'
action:
  service: homeassistant.turn_on
  entity_id: script.bathroom_humidity