id: hippo_psi
alias: 'Check the Hippo tire pressure'
# monitor Hippo tire pressure and alert if it gets below the idea cold PSI
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.the_hippo_tpms_front_right
      - sensor.the_hippo_tpms_rear_right
      - sensor.the_hippo_tpms_front_left
      - sensor.the_hippo_tpms_rear_left
    below: 37.5
action:
  - service: notify.phones
    data_template:
      title: "Below optimal tire pressure"
      message: "{{ trigger.to_state.name }} is {{ trigger.to_state.state |  round(2) }}"