alias: 'Is the hottub going to freeze?'
id: hottub_freezing
# reminder to turn on the hottub if there is a 36 hr period of extended freezing weather in the near future. 
trigger:
  - platform: numeric_state
    entity_id: sensor.temperature_0d
    below: '32'
condition:
  - condition: numeric_state
    entity_id: sensor.temperature_1d
    below: '32'
  - condition: numeric_state
    entity_id: sensor.temperature_2d
    below: '32'    
action:
  - service: notify.phones
    data:
      title: "Freeze Warning"
      message: "Turn on Hot tub - future 12 hr period temps are: {{states('sensor.temperature_0d') }}/{{states('sensor.temperature_1d') }}/{{states('sensor.temperature_2d') }} {{ state_attr('sensor.temperature_2d', 'unit_of_measurement') }}"