alias: 'Open the windows if it is cooler outside than in'
id: open_windows
trigger:
  # when the outside temperature drops within 3 degrees of the inside temperature, this becomes true
  - platform: template
    value_template: "{{ (states('sensor.kbfi_temperature')|float(0)|round(0) - (states('sensor.house_avg_temp')|float(0)|round(0) | int) + 3 ) <= 0 }}"
  # or if the temps in the next 12 hr period is lower than 60 degrees (this will be next morning if triggered after 6pm)
  - platform: template
    value_template: "{{states('sensor.temperature_1d')| int(70) <= 60}}"
condition:
  # the house has to be equal or above 72 degrees F
  - "{{(states('sensor.house_avg_temp')|float(0)|round(0) | int(70)) >= 72 }}"
  # it has to be within four hours of sunset
  - condition: sun
    after: sunset
    after_offset: "-04:00:00"
  # but before its too late
  - condition: time
    before: "22:00:00"
  # and we're home to actually open the windows
  - condition: state
    entity_id: group.presence
    state: "home"
  # and if the furnace is off, it is *probably* summer?
  - condition: state
    entity_id: climate.home
    state: "off"
action:
  - if:
    - alias: "Is it after 6pm?"
      condition: time
      after: "18:00:00"
    then: # shows the temp for the current 12 hour period
    - service: notify.phones
      data:
        title: 'Throw open the windows'
        message: "It is currently {{states('sensor.kbfi_temperature')|float(0)|round(0) | int}}°F outside and {{states('sensor.house_avg_temp')|float(0)|round(0) | int}}°F inside with an overnight low of {{states('sensor.temperature_0d')| int}}°F"    
    else: # shows the temp for the next 12 hour period
    - service: notify.phones
      data:
        title: 'Throw open the windows'
        message: "It is currently {{states('sensor.kbfi_temperature')|float(0)|round(0) | int}}°F outside and {{states('sensor.house_avg_temp')|float(0)|round(0) | int}}°F inside with an overnight low of {{states('sensor.temperature_1d')| int}}°F"