#Theme changes to light mode an hour after sunrise to avoid early morning blinding phone screens. 

alias: Automatic Theme Change - morning
trigger:
  - platform: sun
    offset: "01:00:00"
    event: sunrise
action:
  - service: frontend.set_theme
    data:
      name: 'Google Theme'
