alias: 'Start TV when chromecast starts'
trigger:
  platform: state
  entity_id: media_player.chromecast
  # from: 'off'
  to: 'playing'
condition:
  - condition: state
    entity_id: remote.harmony_hub
    state: 'off'
action:
  service: script.tv_start
