alias: 'Start sound system when living room tv starts'
id: start_tv
trigger:
  platform: state
  entity_id: remote.smart_tv_pro
  # from: 'off'
  to: 'on'
condition:
## Harmony Hub state doesn't consistently update
  # - condition: state
    # entity_id: remote.harmony_hub
    # state: 'off'
action:
  service: remote.send_command
  target:
    entity_id: remote.harmony_hub
  data:
    command:
      - PowerToggle
    device: 40193695
