alias: 'Stop sound system when living room tv turns off'
id: stop_tv
trigger:
  platform: state
  entity_id: remote.smart_tv_pro
  from: 'on'
  to: 'off'
condition:
# # Harmony Hub state doesn't consistently update
  # - condition: state
    # entity_id: remote.harmony_hub
    # state: 'on'
action:
  service: remote.send_command
  target:
    entity_id: remote.harmony_hub
  data:
    command:
      - PowerToggle
    device: 40193695
