alias: Bathroom Light Switch double-tapped off
trigger:
  # Trigger off double-tap of Light switch
  - platform: event
    event_type: zwave.node_event
    event_data:
      entity_id: zwave.bathroom_lightswitch
      basic_level: 0
action:
  - service: switch.toggle
    entity_id: switch.bathroom_fan_switch
