alias: Bathroom Fan Switch Double Tap
trigger:
  - platform: event
    event_type: zwave.node_event
    event_data:
      entity_id: zwave.bathroom_fan
action:
  - service: light.turn_on
    data_template: 
      brightness_pct: >
        {% if trigger.event.data.value == 255 %}
          100
        {% elif trigger.event.data.value == 0 %}
          4
        {% endif %}
      entity_id: light.bathroom_light