alias: Bathroom Fan Switch double-tapped off
trigger:
  # Trigger off double-tap of Fan switch
  - platform: event
    event_type: zwave.node_event
    event_data:
      entity_id: zwave.bathroom_fan
      basic_level: 0
action:
  - service: light.turn_off
    data:
      entity_id: light.bathroom_lightswitch_level
