#This automation calls a series of scripts to automatically turn off the lights if someone forgets to turn off the bathroom light when they leave. Does not turn them on if they're off when motion is detected (seperate automation for that)
alias: 'Bathroom Movement when light is on'
trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_sensor_motion
    to: 'on'
condition:
  condition: state
  entity_id: light.bathroom_light
  state: 'on'
action:
  service: homeassistant.turn_on
  entity_id: script.timed_light_bathroom