alias: Bathroom Switch Double Tap
id: bathroom_switch_doubletap
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: 8cb32c0ca9f0f5ed4c376b0cb02470fa
action:
  - service: light.turn_on
    data_template: 
      brightness_pct: >
        {% if trigger.event.data.value == 255 %}
          100
        {% elif trigger.event.data.value == 0 %}
          4
        {% endif %}
      entity_id: light.bathroom_light