#This automation calls a series of scripts to automatically turn on the bathroom lights if motion is sensed during the correct conditions, then automatically turn them off after the person has left
alias: 'Bathroom Movement when light is off'
trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_sensor_motion
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 4
    - condition: state
      entity_id: group.all_lights
      state: 'on'
    - condition: state
      entity_id: light.bathroom_light
      state: 'off'
action:
  service: homeassistant.turn_on
  entity_id: script.timed_light_bathroom_dark