alias: 'Bathroom Movement'
trigger:
  - platform: state
    entity_id: sensor.bathroom_sensor_burglar
    to: '8'
condition:
  condition: state
  entity_id: light.bathroom_light
  state: 'on'
action:
  service: homeassistant.turn_on
  entity_id: script.timed_light_bathroom