alias: Bathroom Fan Switch double-tapped on
trigger:
  # Trigger on double-tap of Fan switch
  - platform: event
    event_type: zwave.node_event
    event_data:
      entity_id: zwave.bathroom_fan
      basic_level: 255
action:
  - service: light.turn_on
    data:
      entity_id: light.bathroom_lightswitch_level
      brightness_pct: 4