alias: Bedroom Switch Double Tap
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
     device_id: b5f2fcf85f9b0d26d287adc42f27100a

action:
  - service: light.turn_on
    data_template: 
      brightness_pct: >
        {% if trigger.event.data.value == 255 %}
          100
        {% elif trigger.event.data.value == 0 %}
          10
        {% endif %}
      entity_id: light.bedroom_light