alias: 'Kitchen lights to get coffee'
id: coffee_light
# If the coffee pot is on and the hallway senses someone going to get coffee, turns on the closest kitchen light temporarily 
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.hallway_sensor_motion
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: numeric_state #is it dark?
      entity_id: sun.sun
      attribute: elevation
      below: 4
    - condition: state #is the coffee pot on?
      entity_id: switch.coffee
      state: 'on'
    - condition: state #has anyone already turned on the lights?
      entity_id: light.kitchen_light_2
      state: 'off'
action:
  - service: automation.turn_off # override the default movement automation
    entity_id: automation.kitchen_movement
  - service: light.turn_on #turn on the light closest to the coffee pot
    target:
      entity_id: light.kitchen_light_2
    data:
      brightness_pct: 3
  # Wait for kitchen sensor to sense movement
  - wait_template: "{{ is_state('binary_sensor.kitchen_presence_presence', 'on') }}"
    timeout: "00:10:00"
    continue_on_timeout: true 
  # wait for kitchen to be cleared
  - wait_template: "{{ is_state('binary_sensor.kitchen_presence_presence', 'off') }}"
    timeout: "00:10:00" 
    continue_on_timeout: true
  - service: automation.turn_on # turns the default movement automation back on
    entity_id: automation.kitchen_movement
  - condition: and
    conditions:
      - condition: state #if someone turned on the other kitchen light, leave them be, otherwise turn the light off
        entity_id: light.kitchen_light_1
        state: 'off'
  - service: light.turn_off 
    target:
      entity_id: light.kitchen_light_2        