alias: 'Hallway Movement'
trigger:
  - platform: state
    entity_id: sensor.hallway_motion_sensor_burglar
    to: '8'
condition:
  condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: 3
action:
  service: homeassistant.turn_on
  entity_id: script.timed_light_hallway