alias: Hallway Switch Double Tap
trigger:
  - platform: event
    event_type: zwave.node_event
    event_data:
      entity_id: zwave.hallway_lightswitch
action:
  - service: light.turn_on
    data_template: 
      brightness_pct: >
        {% if trigger.event.data.basic_level == 255 %}
          100
        {% elif trigger.event.data.basic_level == 0 %}
          10
        {% endif %}
      entity_id: light.hallway_lightswitch_level