alias: 'Hallway Movement'
trigger:
  - platform: state
    entity_id: sensor.hallway_motion_sensor_burglar
    to: '8'
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3
    - condition: time
      after: '15:00:00'
      before: '20:30:00'
action:
  service: homeassistant.turn_on
  entity_id: script.timed_light_hallway