alias: Kitchen Switch 2 Double Tap
id: kitchen_switch_2_doubletap
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: 38f0169c956322eb2cb54645abc733be
action:
  - service: light.turn_on
    data_template: 
      brightness_pct: >
        {% if trigger.event.data.value == 255 %}
          100
        {% elif trigger.event.data.value == 0 %}
          10
        {% endif %}
      entity_id: light.kitchen_light_2
  - service: light.turn_on
    data_template: 
      brightness_pct: >
        {% if trigger.event.data.value == 255 %}
          100
        {% elif trigger.event.data.value == 0 %}
          10
        {% endif %}
      entity_id: light.kitchen_light_1