## mmwave based automation 
alias: 'Kitchen light - presence detected'
id: kitchen_movement
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_presence_presence
    to: 'on'
    id: 'on'
  - platform: state
    entity_id: binary_sensor.kitchen_presence_presence
    to: 'off'
    id: 'off'
    for:
      minutes: 1 # adjust as necessary 
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
          - condition: state
            entity_id: light.all_kitchen_lights
            state: 'off'
      # temporary time condition so that it doesn't trigger during hours when we might want to go back to sleep
      # will eventually remove once BLE presence and sleep confidence comes into play
          - condition: time
            before: "22:00:00"
            after: "05:00:00"
        sequence:
        - action: light.turn_on
          data_template:
            entity_id: light.all_kitchen_lights
            transition: 2
            # brightness set to 3 between 7pm and 7am, 30 between 5pm and 7pm and 100 between 8am and 5pm.
            brightness: >- 
              {%- if now().strftime('%H')|int >=19 -%}
                {{3|int}}
              {%- elif now().strftime('%H')|int >=17 -%}
                {{30|int}}
              {%- elif now().strftime('%H') |int >=8 -%}
                {{100|int}}
              {%- else -%}
                {{20|int}}
              {%- endif -%}

  - choose:
      - conditions: 
          - condition: trigger
            id: "off"      
        sequence:
        - action: light.turn_off
          target:
            entity_id: light.all_kitchen_lights
mode: single