alias: Kitchen Switch 1 Double Tap
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: 7d27e04aa4d14b076542e5b92dc999a0
action:
  - service: light.turn_on
    data_template: 
      brightness_pct: >
        {% if trigger.event.data.value == 255 %}
          100
        {% elif trigger.event.data.value == 0 %}
          10
        {% endif %}
      entity_id: light.kitchen_light_1
  - service: light.turn_on
    data_template: 
      brightness_pct: >
        {% if trigger.event.data.value == 255 %}
          100
        {% elif trigger.event.data.value == 0 %}
          10
        {% endif %}
      entity_id: light.kitchen_light_2