## mmwave based automation 
alias: 'Office light - presence detected'
id: office_movement
trigger:
  - platform: state
    entity_id: binary_sensor.office_presence_presence
    to: 'on'
    id: 'on'
  - platform: state
    entity_id: binary_sensor.office_presence_presence
    to: 'off'
    id: 'off'
    for:
      minutes: 1 # adjust as necessary 
action:
  - choose:
      - conditions: 
          - condition: trigger
            id: "on"
          - condition: state
            entity_id: light.office_light
            state: 'off'
          # extended hours
          - condition: time
            before: "22:00:00"
            after: "06:00:00"
        sequence:
          - action: light.turn_on
            data_template:
              entity_id: light.office_lamp
              transition: 2
              # brightness set to 3 between 7pm and 7am, 30 between 5pm and 7pm and 100 between 8am and 5pm.
              brightness: >- 
                {%- if now().strftime('%H')|int >=19 -%}
                  {{3|int}}
                {%- elif now().strftime('%H')|int >=17 -%}
                  {{30|int}}
                {%- elif now().strftime('%H') |int >=8 -%}
                  {{100|int}}
                {%- else -%}
                  {{20|int}}
                {%- endif -%}
          - choose:
            - conditions:
                - condition: trigger
                  id: "on"
                - condition: state
                  entity_id: light.office_light
                  state: 'off'
                # during work hours
                - condition: time
                  before: "18:00:00"
                  after: "08:00:00"
              sequence:
              - action: light.turn_on
                data_template:
                  entity_id: light.office_light
                  transition: 2
                  # brightness set to 3 between 7pm and 7am, 30 between 5pm and 7pm and 100 between 8am and 5pm.
                  brightness: >- 
                    {%- if now().strftime('%H')|int >=19 -%}
                      {{3|int}}
                    {%- elif now().strftime('%H')|int >=17 -%}
                      {{30|int}}
                    {%- elif now().strftime('%H') |int >=8 -%}
                      {{100|int}}
                    {%- else -%}
                      {{20|int}}
                    {%- endif -%}
  - choose:
      - conditions: 
          - condition: trigger
            id: "off"      
        sequence:
        - action: light.turn_off
          target:
            entity_id: light.office_light
        - action: light.turn_off
          target:
            entity_id: light.office_lamp
mode: single