alias: 'Turn on the porch light'
triggers: 
    # front door opened
  - trigger: state
    entity_id: binary_sensor.front_door_sensor_window_door_is_open
    from: 'off'
    to: 'on'
    # we get home
  - trigger: state
    entity_id: !include ../../devices.yaml
    from: 'not_home'
    to: 'home'
    # door is unlocked
  - trigger: state
    entity_id: lock.lock_front_door_lock
    from: 'locked'
    to: 'unlocked'   
condition:
  # is it dark
  - condition: template
    value_template: '{{ state_attr("sun.sun", "elevation") < 4 }}'
  # has nothing else already turned the light on
  - condition: state 
    entity_id: switch.porch_light
    state: 'off'
action:
  - service: switch.turn_on
    target:
      entity_id: switch.porch_light
  - wait_template: "{{ is_state('binary_sensor.front_door_sensor_window_door_is_open', 'off') }}"
    timeout: "00:05:00"
  # so it doesn't blink off right after the door is shut
  - delay: "00:02:00"
  - service: switch.turn_off
    target:
      entity_id: switch.porch_light      