alias: 'Turn on the porch light when the door opens'
trigger: 
  - trigger: state
    entity_id: binary_sensor.front_door_sensor_window_door_is_open
    from: 'off'
    to: 'on'
condition:
  # is it dark
  - condition: state 
    entity_id: sun.sun
    state: 'below_horizon'
  # has nothing else already turned the light on
  - condition: state 
    entity_id: switch.porch_light
    state: 'off'
action:
  - service: switch.turn_on
    target:
      entity_id: switch.porch_light
  - wait_template: "{{ is_state('binary_sensor.front_door_sensor_window_door_is_open', 'off') }}"
    timeout: "00:03:00"
  # so it doesn't blink off right after the door is shut
  - delay: "00:02:00"
  - service: switch.turn_off
    target:
      entity_id: switch.porch_light      