alias: Spare Bedroom Switch Double Tap
id: spare_bedroom_switch_double_tap
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: 035feddac732eb4681d7fb3800f2fd56
action:
  - service: light.turn_on
    data_template: 
      brightness_pct: >
        {% if trigger.event.data.value == 255 %}
          100
        {% elif trigger.event.data.value == 0 %}
          10
        {% endif %}
      entity_id: light.spare_bedroom_light