## mmwave based automation 
alias: 'Spare Bedroom light - presence detected'
id: spare_bedroom_movement
trigger:
  - platform: state
    entity_id: binary_sensor.spare_bedroom_presence_presence
    to: 'on'
    id: 'on'
  - platform: state
    entity_id: binary_sensor.spare_bedroom_presence_presence
    to: 'off'
    id: 'off'
    for:
      minutes: 1 # adjust as necessary 
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
          - condition: state
            entity_id: light.spare_bedroom_light
            state: 'off'
          - condition: state
            entity_id: input_boolean.spare_bedroom_light_auto_on
            state: 'on'
        sequence:
        - action: light.turn_on
          data_template:
            entity_id: light.spare_bedroom_light
            transition: 2
            # brightness set to 3 between 7pm and 7am, 30 between 5pm and 7pm and 100 between 8am and 5pm.
            brightness: >- 
              {%- if now().strftime('%H')|int >=19 -%}
                {{3|int}}
              {%- elif now().strftime('%H')|int >=17 -%}
                {{30|int}}
              {%- elif now().strftime('%H') |int >=8 -%}
                {{100|int}}
              {%- else -%}
                {{20|int}}
              {%- endif -%}
  - choose:
      - conditions: 
          - condition: trigger
            id: "off"      
        sequence:
        - action: light.turn_off
          target:
            entity_id: light.spare_bedroom_light
mode: single