alias: 'Trevor Sunrise Alarm'
trigger:
  - platform: mqtt
    topic: 'trevor/alarm'
action:
# triggers coffee script which only runs if input_boolean.coffee_set was toggled
  - service: homeassistant.turn_on
    entity_id: script.coffee_start
  - choose:
    - conditions:
# checks to see if we want both lamps to be used
      - condition: state
        entity_id: input_boolean.one_two_lamps
        state: "on"
      sequence:
        - service: light.turn_on
          entity_id: light.bedroom_color_2
          data:
            brightness_pct: 1
            rgb_color: [255,0,0]
# always turns on my lamp
  - service: light.turn_on
    entity_id: light.bedroom_color_1
    data:
      brightness_pct: 1
      rgb_color: [255,0,0]
  - delay: "00:00:10"
  - choose:
    - conditions:
# continues including the 2nd lamp in the automation if desired
      - condition: state
        entity_id: input_boolean.one_two_lamps
        state: "on"
      sequence:
        - service: light.turn_on
          entity_id: light.bedroom_color_2
          data:
            brightness_pct: 100
            kelvin: 2700
            # 360 seconds = 6 minutes
            transition: 260
# resets the input_boolean back to one lamp
        - service: input_boolean.turn_off
          entity_id: input_boolean.one_two_lamps
  - service: light.turn_on
    entity_id: light.bedroom_color_1
    data:
      brightness_pct: 100
      kelvin: 2700
      # 360 seconds = 6 minutes
      transition: 260
