alias: 'Trevor Sunrise Alarm'
trigger:
  - platform: mqtt
    topic: 'trevor/alarm'
action:
  - service: homeassistant.turn_on
    entity_id: script.coffee_start
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.one_two_lamps
        state: "on"
      sequence:
        - service: light.turn_on
          entity_id: light.bedroom_color_2
          data:
            brightness_pct: 1
            rgb_color: [255,0,0]
  - service: light.turn_on
    entity_id: light.bedroom_color_1
    data:
      brightness_pct: 1
      rgb_color: [255,0,0]
  - delay: "00:00:10"
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.one_two_lamps
        state: "on"
      sequence:
        - service: light.turn_on
          entity_id: light.bedroom_color_2
          data:
            brightness_pct: 100
            kelvin: 2700
            # 360 seconds = 6 minutes
            transition: 260
        - service: input_boolean.turn_off
          entity_id: input_boolean.one_two_lamps
  - service: light.turn_on
    entity_id: light.bedroom_color_1
    data:
      brightness_pct: 100
      kelvin: 2700
      # 360 seconds = 6 minutes
      transition: 260
#wait 5 min and turn on kitchen light if coffee was brewed
  - condition: and
    conditions:
      - condition: state
        entity_id: switch.coffee
        state: 'on'
      - condition: state
        entity_id: light.kitchen_light_2
        state: 'off'
  - delay: "00:05:00"     
  - service: light.turn_on
    entity_id: light.kitchen_light_2
    data:
      brightness_pct: 10