alias: 'it is getting dark'
trigger:
  platform: sun
  event: sunset
  offset: "-00:45:00"
condition:
  - condition: state
    entity_id: group.presence
    state: home
  - condition: state
    entity_id: light.dining_lights
    state: 'off'       
action:
  - service: light.turn_on
    entity_id: light.dining_lights
    data:
      brightness_pct: 1
  - delay: "00:00:01"
  - service: light.turn_on
    entity_id: light.dining_lights
    data:
      brightness_pct: 100
      # 900 seconds = 15 minutes
      transition: 900