alias: Keypad temporary code end
trigger:
  - platform: state
    to: 'True'
    entity_id:
      - sensor.keypad_1_temp_lock_turn_off
      - sensor.keypad_2_temp_lock_turn_off
      - sensor.keypad_3_temp_lock_turn_off
      - sensor.keypad_4_temp_lock_turn_off
      - sensor.keypad_5_temp_lock_turn_off
      - sensor.keypad_6_temp_lock_turn_off
      - sensor.keypad_7_temp_lock_turn_off
      - sensor.keypad_8_temp_lock_turn_off
      - sensor.keypad_9_temp_lock_turn_off
      - sensor.keypad_10_temp_lock_turn_off
      - sensor.keypad_11_temp_lock_turn_off
      - sensor.keypad_12_temp_lock_turn_off
      - sensor.keypad_13_temp_lock_turn_off
      - sensor.keypad_14_temp_lock_turn_off
      - sensor.keypad_15_temp_lock_turn_off
# this is where usercodes get deleted, for the Schlage locks there seems to be an issue with 
# clear usercode, setting to 0000 works for some locks, but for the schalge it sets 0000 as above
# valid code, so this sets a random code, of course that means there is an unknown code in the cleared
# slots.  If you dont like that set a specific code that only you know
action:
  - service: lock.set_usercode
    data_template:
      usercode: !secret primary_code
      # usercode: >-
        # {{ range(1000, 9999) | random }}
# Front Door Deadbolt.  You must put in the zwave node id's here 
      node_id: 2
      code_slot: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = object_id[7:-19] %}
        {{ code_slot }}
        
  - service: lock.set_usercode
    data_template:
      usercode: >-
        {{ range(1000, 9999) | random }}


  # - service: notify.pushbullet_notifications
    # data_template:
      # message: >-
        # {% set object_id = trigger.to_state.object_id %}
        # {% set code_slot = object_id[7:-19] %}
        # {% set usercode_input = 'door_keypad_' ~ code_slot ~ '_code' %}
        # {% set usercode = states['input_text'][usercode_input].state %}
        # {% set name_input = 'door_keypad_' ~ code_slot ~ '_name' %}
        # {% set name = states['input_text'][name_input].state %}
        # The pin code {{ usercode }} for {{ name }} has now been removed from all doors.
      # title: "Beach House: Temporary code disabled on all doors"        
      # target:
      # - !secret pauls_secret_email
      # - !secret tracys_secret_email

  - condition: and
    conditions:
      - condition: template
        value_template: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = object_id[7:-19] %}
          {% set input = 'door_keypad_' ~ code_slot ~ '_access_schedule' %}
          {% set input_value = states['input_select'][input].state %}
          {{ input_value == 'Temporary' }}

  - service: script.turn_on
    data_template:
      entity_id: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = object_id[7:-19] %}
        {{ 'script.door_keypad_' ~ code_slot ~ '_delete' }}
