alias: Keypad switch turned on
trigger:
  - platform: state
    to: 'on'
    entity_id:
# Entities need to be named to match your lock name.  In this case
# front, back, garage based on "lock.lock_front_door_lock", etc
      - input_boolean.door_keypad_1_front_switch
      - input_boolean.door_keypad_2_front_switch
      - input_boolean.door_keypad_3_front_switch
      - input_boolean.door_keypad_4_front_switch
      - input_boolean.door_keypad_5_front_switch
      - input_boolean.door_keypad_6_front_switch
      - input_boolean.door_keypad_7_front_switch
      - input_boolean.door_keypad_8_front_switch
      - input_boolean.door_keypad_9_front_switch
      - input_boolean.door_keypad_10_front_switch
      - input_boolean.door_keypad_11_front_switch
      - input_boolean.door_keypad_12_front_switch
      - input_boolean.door_keypad_13_front_switch
      - input_boolean.door_keypad_14_front_switch
      - input_boolean.door_keypad_15_front_switch
      - input_boolean.door_keypad_16_front_switch
      - input_boolean.door_keypad_17_front_switch
      - input_boolean.door_keypad_18_front_switch
condition:
  - condition: template
    value_template:  >-
      {% set object_id = trigger.to_state.object_id %}
      {% set code_slot = "_".join(object_id.split("_")[2:-2]) %}
      {% set select_id = 'door_keypad_' ~ code_slot ~ '_access_schedule' %}
      {{ states['input_select'][select_id].state in ['Always', 'Enabled'] }}
action:

  - service: lock.set_usercode
    data_template:
      node_id: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set lock_name = "_".join(object_id.split("_")[3:-1]) %}
        {% set lock_id = 'lock_' ~ lock_name ~ '_door_lock' %}
        {{ states['lock'][lock_id].attributes.node_id }}
        
      code_slot: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = "_".join(object_id.split("_")[2:-2]) %}
        {{ code_slot }}

      usercode: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = "_".join(object_id.split("_")[2:-2]) %}
        {% set user_code_id = 'door_keypad_' ~ code_slot ~ '_code' %}
        {{ states['input_text'][user_code_id].state }}
