alias: Keypad clear code after one time use is set to disabled for 16 through 18
# This will also delete the code from all doors when you change the option from enabled to disabled
trigger:
  - platform: state
    to: 'Disabled'
    entity_id:
      - input_select.door_keypad_16_access_schedule
      - input_select.door_keypad_17_access_schedule
      - input_select.door_keypad_18_access_schedule
action:
  - service: script.turn_on
    data_template:
      entity_id: >
            {% set object_id = trigger.to_state.entity_id %}
            {% set code_slot = "_".join(object_id.split("_")[3:-2]) %}
            {% set script_to_run = 'script.door_keypad_' ~ code_slot ~ '_delete' %}
            {{ script_to_run }}
