alias: Keypad temporary code start (Front)
trigger:
  - platform: state
    to: 'True'
    entity_id:
      - sensor.keypad_1_temp_lock_turn_on
      - sensor.keypad_2_temp_lock_turn_on
      - sensor.keypad_3_temp_lock_turn_on
      - sensor.keypad_4_temp_lock_turn_on
      - sensor.keypad_5_temp_lock_turn_on
      - sensor.keypad_6_temp_lock_turn_on
      - sensor.keypad_7_temp_lock_turn_on
      - sensor.keypad_8_temp_lock_turn_on
      - sensor.keypad_9_temp_lock_turn_on
      - sensor.keypad_10_temp_lock_turn_on
      - sensor.keypad_11_temp_lock_turn_on
      - sensor.keypad_12_temp_lock_turn_on
      - sensor.keypad_13_temp_lock_turn_on
      - sensor.keypad_14_temp_lock_turn_on
      - sensor.keypad_15_temp_lock_turn_on
# if you changed the name of your switch from "front" change below to match
condition:
  - condition: template
    value_template: >-
      {% set object_id = trigger.to_state.object_id %}
      {% set code_slot = object_id[7:-18] %}
      {% set input = 'door_keypad_' ~ code_slot ~ '_front_switch' %}
      {{ states['input_boolean'][input].state == 'on' }}

action:
  - service: lock.set_usercode
    data_template:
      usercode: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = object_id[7:-18] %}
        {% set input = 'door_keypad_' ~ code_slot ~ '_code' %}
        {{ states['input_text'][input].state }}

      node_id: >-
        {{ states['lock']['front_door_lock'].attributes.node_id }}

      code_slot: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = object_id[7:-18] %}
        {{ code_slot }}

  # - service: notify.pushbullet_notifications
    # data_template:
      # message: >-
        # {% set object_id = trigger.to_state.object_id %}
        # {% set code_slot = object_id[7:-18] %}
        # {% set usercode_input = 'door_keypad_' ~ code_slot ~ '_code' %}
        # {% set usercode = states['input_text'][usercode_input].state %}
        # {% set name_input = 'door_keypad_' ~ code_slot ~ '_name' %}
        # {% set name = states['input_text'][name_input].state %}
        # {% set start_input = 'door_keypad_' ~ code_slot ~ '_date_start' %}
        # {% set start = states['input_datetime'][start_input].state %}
        # {% set end_input = 'door_keypad_' ~ code_slot ~ '_date_end' %}
        # {% set end = states['input_datetime'][end_input].state %}
        # The pin code {{ usercode }} is now temporarily enabled for {{ name }} from {{ start }} to {{ end }}.

      # title: >-
        # {% set object_id = trigger.to_state.object_id %}
        # {% set code_slot = object_id[7:-18] %}
        # {% set switch_input = 'door_keypad_' ~ code_slot ~ '_front_switch' %}
        # {% set switch_name = states['input_boolean'][switch_input].attributes.friendly_name %}
        # Beach House: Temporary code enabled on {{ switch_name }}
      # target:
      # - !secret pauls_secret_email
