alias: Notify who unlocked door with timestamp
# this will send you a message telling you which slot was used to unlock the door and will use the
# name set in the input text for the door as it's friendly name.  If you dont want to get notified
# when you are home use the appropiate condition. 
trigger:
- platform: state
  entity_id:
    - sensor.frontdoor_action
  to: 'Keypad Unlock'
condition:
- condition: numeric_state
  entity_id: sensor.ha_runtime_in_minutes
  above: 1
- condition: state
  entity_id: binary_sensor.people_home
  state: 'off'
action:
- service: input_boolean.turn_on
  entity_id: input_boolean.guests_present
- delay:
    seconds: 2
# - service: notify.pushbullet_notifications
  # data_template:
    # message: " At {{ as_timestamp (now()) | timestamp_custom('%I:%M %p') }} on {{ now().strftime('%d %b %Y') }} " 
    # target:
    # - !secret pauls_secret_email
    # - !secret tracys_secret_email
    # title: >
      # {% set mapper = { 'sensor.frontdoor_action' : 'sensor.frontdoor_code' } %}
      # {{ trigger.to_state.attributes.friendly_name }} unlocked by {{ states(mapper[trigger.entity_id]) }}
- service: input_text.set_value
  data_template:
    entity_id: input_text.last_person_to_unlock
    value: >
      {% set mapper = { 'sensor.frontdoor_action' : 'sensor.frontdoor_code' } %}
      {{ states(mapper[trigger.entity_id]) }}
