alias: 'Unlock Front Door Upon Arrivial'
trigger:
  platform: state
  entity_id:
    - person.trevor
    - person.emily
    - device_tracker.the_hippo_location_tracker
  from: 'not_home'
  to: 'home'
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: lock.lock_front_door_lock
    state: 'locked'
  - condition: time
    after: '06:00:00'
    before: '23:00:00'
action:
  - service: lock.unlock
    entity_id: lock.lock_front_door_lock
  - wait_template: "{{ is_state('binary_sensor.front_door_sensor_window_door_is_open', 'on') }}"
    timeout: "00:05:00"
  - service: script.relock_front_door