alias: 'Unlock Front Door Upon Arrivial'
trigger:
  platform: state
  entity_id:
    - person.trevor
    - person.emily
  from: 'not_home'
  to: 'home'
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: lock.lock_front_door_lock
    state: 'locked'
  - condition: time
    after: '07:00:00'
    before: '22:00:00'
action:
  - service: lock.unlock
    entity_id: lock.lock_front_door_lock
  - delay: '00:03:00'
  - service: script.relock_front_door