# Once the system has seen we have all left, set thermostat to away


alias: 'Goodbye Climate'
trigger:
  platform: state
  entity_id: group.climate_presence
  from: 'home'
  to: 'not_home'
action:
  - service: climate.set_away_mode
    data:
      entity_id: climate.home
      away_mode: on
