alias: 'Someone has Arrived'
trigger:
  platform: state
  entity_id: !include ../../devices.yaml
  from: 'not_home'
  to: 'home'
### currently useless as group.family is always home when we arrive home (simultaneous trigger).
# condition:
  # - condition: state
    # entity_id: group.family
    # state: 'home'
# so it won't interrupt music currently playing. No way to restart.
condition:
  condition: and
  conditions:
  - condition: time
    after: '07:00:00'
    before: '22:00:00'
  - condition: or
    conditions:
    - condition: state
      entity_id: group.media
      state: 'off'
    - condition: state
      entity_id: group.media
      state: 'idle'

action:
  - service: tts.google_say
    data_template:
      entity_id: media_player.home_group
      language: en
      message: > 
        Just to let you know, {{ trigger.to_state.attributes.friendly_name }} is here.
