# Once the system has seen we have all left, make certain the door is locked, etc...

alias: 'Goodbye Sequence'
trigger:
  platform: state
  entity_id: group.presence
  from: 'home'
  to: 'not_home'
action:
  - service: script.relock_front_door
  - service: light.turn_off
    entity_id: all
