alias: 'Welcome Home Lights'
trigger: 
  platform: state
  entity_id: !include ../../devices.yaml
  from: 'not_home'
  to: 'home'
condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  # - condition: state
    # entity_id: light.living_room
    # state: 'off'     
action:
  # - service: light.turn_on
    # entity_id: light.living_room
    # data:
      # brightness_pct: 30
  - service: switch.turn_on
    target:
      entity_id: switch.porch_light
  - delay: '00:10:00'
  - service: switch.turn_off
    target:
      entity_id: switch.porch_light  