alias: 'Welcome Home Lights'
trigger: 
  platform: state
  entity_id: !include ../../devices.yaml
  from: 'not_home'
  to: 'home'
condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
action:
  - service: light.turn_on
    entity_id: light.living_room
    data:
      brightness_pct: 30