alias: 'Plant Schedule - Off'
id: plant_schedule_off
trigger:
  - platform: time
    at: "19:45:00"
condition:
  condition: state
  entity_id: group.plants
  state: 'on'
action:
  service: homeassistant.turn_off
  entity_id: group.plants