alias: 'Plant Schedule - On'
trigger:
  - platform: time
    at: "07:30:00"
condition:
  condition: state
  entity_id: group.plants
  state: 'off'
  
action:
# delays the plant lights 60 min if it is not a work day to avoid disturbing sleepers
  - delay: "{{ iif(is_state('binary_sensor.workday_sensor', 'off'), '01:00:00', '00:00:01') }}"
  - service: homeassistant.turn_on
    entity_id: group.plants    
